stages:
  - build
  - deploy

build:
    image: docker
    services:
        - docker:dind
    stage: build
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/dygufa/memuy_api:v$CI_PIPELINE_ID .
        - docker push registry.gitlab.com/dygufa/memuy_api:v$CI_PIPELINE_ID

deploy:
  stage: deploy
  only:
    - master
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/\$CI_PIPELINE_ID/${CI_PIPELINE_ID}/g" deploy/app.yml
    - sed -i "s~\$MONGO_URL~${MONGO_URL}~g" deploy/app.yml
    - sed -i "s/\$PORT/${PORT}/g" deploy/app.yml
    - sed -i "s~\$NODE_ENV~${NODE_ENV}~g" deploy/app.yml
    - sed -i "s/\$AWS_ACCESS_KEY_ID/${AWS_ACCESS_KEY_ID}/g" deploy/app.yml
    - sed -i "s~\$AWS_SECRET_ACCESS_KEY~${AWS_SECRET_ACCESS_KEY}~g" deploy/app.yml
    - sed -i "s/\$S3_BUCKET/${S3_BUCKET}/g" deploy/app.yml
    - sed -i "s~\$SENTRY_DNS~${SENTRY_DNS}~g" deploy/app.yml
    - cat deploy/*.yml > tmp
    - kubectl apply -f tmp