name: Deploy
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to ECR
        run: eval $(aws ecr get-login --no-include-email --region us-east-1)
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Build & Publish
        run: |
          docker build . -t 426782010323.dkr.ecr.us-east-1.amazonaws.com/memuy_api:${{ github.sha }}
          docker push 426782010323.dkr.ecr.us-east-1.amazonaws.com/memuy_api:${{ github.sha }}
